spring:
  application:
    name: notification
  profiles:
    default: notification
  config:
    import:
      - optional:file:./soc-config/common/application-common.yml
      - optional:file:./soc-config/log/application-log.yml
      - optional:file:./soc-config/notification/application-notification.yml