spring:
  application:
    name: notification
  profiles:
    default: notification
  config:
    import:
      - optional:classpath:config/common/application-aws.yml
      - optional:classpath:config/common/application-common-${spring.profiles.active}.yml
      - optional:classpath:config/log/application-log.yml
      - optional:classpath:config/notification/application-notification.yml