spring:
  application:
    name: api
  profiles:
    default: dev
  config:
    import:
      - optional:classpath:soc-config/api/application-${spring.profiles.active}.yml
      - optional:classpath:soc-config/common/application-aws.yml
      - optional:classpath:soc-config/common/application-common-${spring.profiles.active}.yml
      - optional:classpath:soc-config/auth/application-auth.yml
      - optional:classpath:soc-config/log/application-log.yml
      - optional:classpath:soc-config/notification/application-notification.yml