spring:
  application:
    name: api
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:config/api/application-${spring.profiles.active}.yml
      - optional:classpath:config/common/application-aws.yml
      - optional:classpath:config/common/application-common-${spring.profiles.active}.yml
      - optional:classpath:config/auth/application-auth.yml
      - optional:classpath:config/log/application-log.yml
      - optional:classpath:config/notification/application-notification.yml