spring:
  application:
    name: api
  profiles:
    default: dev
  config:
    import:
      - optional:file:./soc-config/api/application-dev.yml
      - optional:file:./soc-config/api/application-prod.yml
      - optional:file:./soc-config/common/application-common.yml
      - optional:file:./soc-config/auth/application-auth.yml
      - optional:file:./soc-config/log/application-log.yml
      - optional:file:./soc-config/notification/application-notification.yml