spring:
  application:
    name: auth
  profiles:
    default: auth
  config:
    import:
      - optional:file:./soc-config/common/application-common.yml
      - optional:file:./soc-config/auth/application-auth.yml
      - optional:file:./soc-config/log/application-log.yml
      - optional:file:./soc-config/notification/application-notification.yml