spring:
  application:
    name: common
  profiles:
    default: common
  config:
    import:
      - optional:classpath:soc-config/common/application-aws.yml
      - optional:classpath:soc-config/common/application-common-${spring.profiles.active}.yml