spring:
  application:
    name: common
  profiles:
    default: common
  config:
    import:
      - optional:classpath:config/common/application-common-${spring.profiles.active}.yml
      - optional:classpath:config/common/application-aws.yml