name: Deploy Blue-Green to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 코드
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 설정
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. Docker Hub 로그인 & 이미지 빌드 & 푸시
      - name: Docker Build & Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 5. SSH → EC2 배포 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chmod +x /home/ec2-user/bin/deploy.sh
            /home/ec2-user/bin/deploy.sh "${{ secrets.DOCKER_USERNAME }}/myapp:latest" "${{ secrets.FCM_KEY_BASE64 }}"
